# Generated by Django 5.1.6 on 2025-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='ไม่ระบุ'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='ไม่ระบุ', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'บัตรเครดิต'), ('paypal', 'PayPal'), ('bank_transfer', 'โอนเงินผ่านธนาคาร'), ('cash_on_delivery', 'เก็บเงินปลายทาง')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
